<?php
/***************************************************************************
*                                extension.inc
 *
 *   Begin date           	: Wednesday, Aug 3, 2005
 *   Copyright            	: (C) 2005 K&G Software Company
 *   Email                	: sales@php5-vn.com
 ***************************************************************************/

defined('PHP5_PHP') or die("Application is stopping!!!");

$php5Ext = ".php";
?>